name: opentelemetry_api
description: Dartastic.io's OpenTelemetry API for Dart following the OpenTelemetry specification.
version: 0.8.0
repository: https://github.com/MindfulSoftwareLLC/opentelemetry_api.git
homepage: https://dartastic.io

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  collection: ^1.19.1
  fixnum: ^1.1.1

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^5.1.1
  test: ^1.25.15
  coverage: ^1.11.1
  protoc_plugin: ^21.1.2
